
CPPFLAGS = -Wno-macro-redefined -Wno-int-to-void-pointer-cast -Wno-unused-value -Werror
# The final executable file
main: main.o Object.o List.o
#	gcc -o main main.o Object.o

# Compile main.c into main.o
# main.o: main.c
# 	gcc -c main.c

# # Compile Object.c into Object.o
# Object.o: Object.c
# 	gcc -c Object.c

# Node.o: Node.c
# 	gcc -c Node.c

# Clean up the build
clean:
	rm -f main main.o Object.o List.o
